# references:
# * http://www.objc.io/issue-6/travis-ci.html

os: osx
osx_image: xcode10.2
language: objective-c

script:
- set -o pipefail && xcodebuild test -workspace Example/RAGTextField.xcworkspace -scheme RAGTextField-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
